# -*- coding: utf-8 -*-
"""NhanDienTraiCay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199lGevDJu6TmZEnfJjLz4YBqd-mRmGHS
"""

from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Conv2D, MaxPooling2D, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler
from keras.utils import np_utils
from sklearn.utils import shuffle
import cv2
import matplotlib.pyplot as plt
import numpy as np
import pickle
import tensorflow as tf
import math as m

with open('data.pickle', 'rb') as f:
    (x_train, y_train) = pickle.load(f)
x_pre_0 = x_train[3]
x_pre_1 = x_train[10]
x_pre_2 = x_train[22]
x_pre_3 = x_train[39]
x_pre_4 = x_train[47]
x_pre_5 = x_train[57]
x_pre_6 = x_train[61]
x_pre_7 = x_train[79]
x_pre_8 = x_train[82]
x_pre_9 = x_train[93]
x_train = x_train.astype('float32')
x_train /= 255
y_train = np_utils.to_categorical(y_train, 10)
x_train, y_train = shuffle(x_train, y_train)

def plot_history(history_fine):
  f1 = history_fine.history['acc']
  val_f1 = history_fine.history['val_acc']
  loss = history_fine.history['loss']
  val_loss = history_fine.history['val_loss']
  plt.figure(figsize=(8, 8))
  plt.subplot(2, 1, 1)
  plt.plot(f1, label='Acc')
  plt.plot(val_f1, label='Validation Acc')
  plt.legend(loc='lower right')
  plt.title('Accuracy')
  plt.subplot(2, 1, 2)
  plt.plot(loss, label='Loss')
  plt.plot(val_loss, label='Validation Loss')
  plt.legend(loc='upper right')
  plt.title('Loss')
  plt.xlabel('epoch')
  plt.show()

model = Sequential()
model.add(Conv2D(32, (3,3), activation='relu',kernel_initializer='he_uniform', padding ='same', input_shape = (150,150,3)))
model.add(Conv2D(32, (3,3), activation='relu',kernel_initializer='he_uniform', padding ='same'))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(64, (3,3), activation='relu',kernel_initializer='he_uniform', padding ='same'))
model.add(Conv2D(64, (3,3), activation='relu',kernel_initializer='he_uniform', padding ='same'))
model.add(MaxPooling2D(2,2))
model.add(Conv2D(128, (3,3), activation='relu',kernel_initializer='he_uniform', padding ='same'))
model.add(Conv2D(128, (3,3), activation='relu',kernel_initializer='he_uniform', padding ='same'))
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_initializer='he_uniform'))
model.add(Dense(10, activation='softmax'))
model.summary()

opt = Adam(lr = 0.001)
model.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ['acc'])
his = model.fit(x_train, y_train, epochs = 10, batch_size = 64, validation_split = 0.2)
plot_history(his)

label = ['Cam','Dao','Dua Hau','Du Du','Khe','Le','Oi','Man','Sau Rieng','Xoai']
plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_0.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_0, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_1.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_1, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_2.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_2, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_3.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_3, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_4.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_4, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_5.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_5, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_6.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_6, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_7.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_7, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_8.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_8, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))

plt.title("Loai trai cay duoc du doan la:  " + label[np.argmax(model.predict(x_pre_9.reshape(1,150,150,3)))])
plt.imshow(cv2.cvtColor(x_pre_9, cv2.COLOR_BGR2RGB), cmap=plt.get_cmap('gray'))